# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Docker, kubernetes, java, mysql workstation configuration.
# 02-Aug-2017 Igor Azarny (iazarny@yahoo.com)
# 18-Jul-2019 Igor Azarny (iazarny@yahoo.com)


Vagrant.configure("2") do |config|
    config.vm.box = "generic/fedora28"
    #config.vm.box = "cibt0943/centos7

    config.vm.hostname = "minikube"
    config.vm.boot_timeout = 120
    config.ssh.insert_key = false
    # in case of problems during provision (vagrant cannot login to vm box) uncomment 2 lines below
    #config.ssh.username = "vagrant"
    #config.ssh.password = "vagrant"

    config.vm.network :private_network, type: "dhcp"
    config.vm.network "forwarded_port", guest: 9999, host: 9999
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 22222, host: 22222
    config.vm.network "forwarded_port", guest: 20000, host: 20000
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.network "forwarded_port", guest: 22, host: 22
    config.vm.network "forwarded_port", guest: 8443, host: 8443
    config.vm.network "forwarded_port", guest: 10250, host: 10250


    config.vm.provider :libvirt do |libvirt|
        libvirt.uri = 'qemu+unix:///system'
        libvirt.memory = 6144
        libvirt.cpus = 2
	    libvirt.cpu_feature :name => 'x2apic', :policy => 'disable'
        libvirt.graphics_type = "spice"
        libvirt.video_type = "qxl"
    end


    config.vm.provider "virtualbox" do |vb|
        vb.name = "minikube"
        vb.gui = true
        vb.memory = "6144"
        vb.cpus = 2
    end


#    config.vm.provision "shell", inline: <<-SHELL

# reboot
#        config.vm.provision :reload
#    SHELL



    #config.vm.provision :shell, inline: "mkdir -p /home/vagrant/.m2 && chown vagrant:vagrant /home/vagrant/.m2"
    config.vm.provision "shell", inline: <<-SHELL


#selinux
        setenforce 0
        setenforce Permissive
        sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
        sestatus

#tools
        yum install  -y git   wget curl   net-tools    mc unzip   jq  socat
        dng remove -y memcached
#system 
        iptables -t filter --policy FORWARD ACCEPT
        systemctl disable firewalld
        systemctl stop firewalld
        #systemctl status firewalld	


#java
        dnf search openjdk
        yum install -y java-1.8.0-openjdk-devel

        wget http://www-eu.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
        tar xzvf apache-maven-3.6.1-bin.tar.gz -C /usr/local/
        ln -s /usr/local/apache-maven-3.6.1/bin/mvn /usr/bin/mvn

#docker

        
        dnf install -y docker
        systemctl enable docker.service
        systemctl start docker.service
        
#        usermod -aG docker vagrant

#        newgrp docker
        
        docker run hello-world
        export DOCKER_OPTS="$DOCKER_OPTS --insecure-registry=localhost:5000"
        docker run -d -p 5000:5000 --restart=always --name registry registry:2
        service docker restart
        docker pull alpine
        docker tag alpine localhost:5000/local-alpne
        docker push localhost:5000/local-alpine

#k8s
         #---------------------------------
        #curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
        #install minikube /usr/local/bin
        #-------------------------------------------------------------
        #wget -q --show-progress --https-only --timestamping  https://storage.googleapis.com/kubernetes-release/release/v1.13.8/bin/linux/amd64/kubectl 
        #      https://storage.googleapis.com/kubernetes-release/release/v1.13.8/bin/linux/amd64/kube-proxy \
        #      https://storage.googleapis.com/kubernetes-release/release/v1.13.8/bin/linux/amd64/kubelet

        #mkdir -p  /var/lib/kubelet  /var/lib/kube-proxy  /var/lib/kubernetes
        #chmod +x kube-proxy kubelet kubectl 
        #mv  kube-proxy kubelet kubectl /usr/local/bin/

        #wget -O dind-cluster.sh https://github.com/kubernetes-sigs/kubeadm-dind-cluster/releases/download/v0.2.0/dind-cluster-v1.13.sh 
        #chmod +x dind-cluster.sh

        #dind-cluster.sh up

         #---------------------------------
#yum provides semanage
#curl -sfL https://get.k3s.io | sh -
 
         #---------------------------------

        #curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        
        #systemctl enable kubelet.service

        #kubeadm config images pull

        #minikube start --vm-driver=none --dns-domain='cluster.local'   --wait=true --kubernetes-version v1.13.8 
        #minikube start --vm-driver=none --dns-domain='cluster.local'   --wait=true --kubernetes-version v1.13.8 --extra-config=kubeadm.ignore-preflight-errors=SystemVerification


#systemctl enable kubelet.service

#--extra-config=apiserver.ServiceClusterIPRange=10.0.0.0/24 -p azcl

#build

        #git clone https://github.com/iazarny/msstarter2.git
        #mvn clean install fabric8:build fabric8:push

#----------------------------------------------------
#kubectl create -f k8s/deploy-all.yml
      
    SHELL


end
