########################################################################################################################
# Deployment. Gateway and web server
########################################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: gw-st-2
  name: gw-st-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gw-st-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: gw-st-2
    spec:
      containers:
      - image: localhost:5000/gw-st-2:2
        imagePullPolicy: Always
        name: gw-st-2
        ports:
        - containerPort: 20000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /index.html#/
            port: 20000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      initContainers:
      - name: rest-st-2
        image: busybox
        command: ['sh', '-c', 'until nslookup rest-st-2; do echo waiting for rest-st-2; sleep 10; done;']
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
########################################################################################################################
# Service. Gateway and Web Server
########################################################################################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gw-st-2
  name: gw-st-2
  namespace: default
spec:
  ports:
  - port: 20000
    targetPort: 20000
  selector:
    run: gw-st-2
  sessionAffinity: None
  type: LoadBalancer


