########################################################################################################################
# Deployment. Rest
########################################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: st-rest-2
  name: st-rest-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: st-rest-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: st-rest-2
    spec:
      containers:
      - image: localhost:5000/st-rest-2
        imagePullPolicy: Always
        name: st-rest-2
        ports:
        - containerPort: 22222
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /application/env
            port: 222222
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
########################################################################################################################
# Service. Internal. Rest
########################################################################################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    run: st-rest-2
  name: st-rest-2
  namespace: default
spec:
  ports:
  - port: 22222
    targetPort: 22222
  selector:
    run: st-rest-2
  sessionAffinity: None
  type: LoadBalancer


