info:
  version: 2




spring:
  datasource:
    url: jdbc:derby:mydb;create=true
    username: root
    password: password
    schema:
      - classpath:/schema.sql
    data:
      - classpath:/data.sql
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
        connection.release_mode: on_close
        globally_quoted_identifiers: true


server:
  port: ${PORT:22222}
  security:
    enabled: false


error:
  whitelabel:
    enabled:false

logging:
  file: logs/rest-service.log
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, logfile, configprops, httptrace



