info:
  version: @version@


spring:
  datasource:
    url: jdbc:derby:mydb;create=true
    username: root
    password: password
  jpa:
    #hibernate.ddl-auto: validate
    hibernate.ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
#        cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        connection.release_mode: on_close
        globally_quoted_identifiers: true


server:
  port: ${PORT:22222}
  security:
    enabled: false


error:
  whitelabel:
    enabled:false

logging:
  file: logs/rest-service.log
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, logfile, configprops, httptrace



