info:
  version: 2



spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection.release_mode: on_close
        globally_quoted_identifiers: true
    show-sql: true


server:
  port: ${PORT:22222}
  security:
    enabled: false


error:
  whitelabel:
    enabled:false

logging:
  file: logs/rest-service.log
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, logfile, configprops, httptrace



